name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-net-latest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET latest
      uses: actions/setup-dotnet@v1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore    

    - name: Test .Net
      run: dotnet test Tedd.SpanUtils.Tests/Tedd.SpanUtils.Tests.csproj --no-build --verbosity normal

    - name: Build .Net Framework tests (legacy)
      run: dotnet build --no-restore Tedd.SpanUtils.DotNet4Tests\Tedd.SpanUtils.DotNet4Tests.csproj

    - name: Test .Net Framework (legacy)
      run: ../xunit/xunit.console.exe Tedd.SpanUtils.DotNet4Tests\bin\Release\net462\Tedd.SpanUtils.DotNet4Tests.dll


    #- name: Create Build Directory
    #  run: mkdir Build
    #- name: Build
    #  run: |
    #    msbuild.exe Tedd.SpanUtils.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="Build"

