name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build-netframework:
    runs-on: windows-latest

#    defaults:
#      run:
#        working-directory: ./src
        
    steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore Packages
      run: nuget restore src/Tedd.SpanUtils.sln
    
    - name: Create Build Directory
      run: mkdir Build
    
    - name: Build Solution

      run: |
        msbuild.exe src/Tedd.SpanUtils.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../Build"
